server:
  addr: ":8080"

db:
  dsn: "postgres://postgres:postgres@127.0.0.1:5432/dora_pay?sslmode=disable"

wallet:
  xpub: "xpub6EKP71RFazTC4hH5adTpWBmb4EiFQCK8CysUpNcRvbNUr9T7oyCJLa2ef1mokidNae1FiZzLEp56BdeURf4yC7jaCmgR1xKz7xcDvhZ1vx2"

chain:
  chain_id: "vota-testnet"
  rpc_endpoint: "https://vota-testnet-rpc.dorafactory.org/"
  denom: "peaka"
  decimals: 18
  bech32_prefix: "dora"
  confirm_depth: 2

orders:
  min_credit: 10000
  ttl_minutes: 10

worker:
  start_height: 11450743

pricing:
  fixed_credit_per_dora: 100
